### ISSUE TITLE
"each" is deprecated

### ISSUE THREAD

**Issue by nam-truong-le** [asiapay-lib/asiapay-Woocommerce#6]
[This line](https://github.com/asiapay-lib/asiapay-Woocommerce/blob/06d85d3eb12009864dc497b4abe0094b26cfd29e/paydollar-payment-gateway-woocommerce/index.php#L358) uses "each" that is deprecated. Would you mind fixing it? Thank you.

**Comment by apphit-christian** [comment]
Thank you for reporting. We will upload an updated version to fix this.

**Comment by apphit-christian** [comment]
@nam-truong-le it is fixed and may try https://github.com/asiapay-lib/asiapay-Woocommerce/releases/latest
