### ISSUE TITLE
Cannot upload from wordpress and the plugin is not updated since 2 years. Please help

### ISSUE THREAD

**Issue by jazz047** [asiapay-lib/asiapay-Woocommerce#9]
Cannot upload from wordpress and the plugin is not updated since 2 years. Please help

**Comment by asiapay-lib** [comment]
Hi jazz047, 
we've released the latest version of the plugin! You can find it here: [GitHub Latest Release](https://github.com/asiapay-lib/asiapay-Woocommerce/releases/latest). 
To upload it directly in WordPress, download the ZIP file and upload it via the WordPress plugin uploader. 
Let us know if you need any further assistance. Thanks!"

**Comment by jazz047** [comment]
Hi,

Thank you very much. Now is work very well on wordpress. Than k you for the update.

De : AsiaPay ***@***.***>
Envoyé : Tuesday, November 5, 2024 6:54 PM
À : asiapay-lib/asiapay-Woocommerce ***@***.***>
Cc : jazz047 ***@***.***>; Author ***@***.***>
Objet : Re: [asiapay-lib/asiapay-Woocommerce] Cannot upload from wordpress and the plugin is not updated since 2 years. Please help (Issue #9)


Hi jazz047,
we've released the latest version of the plugin! You can find it here: GitHub Latest Release<https://github.com/asiapay-lib/asiapay-Woocommerce/releases/latest>.
To upload it directly in WordPress, download the ZIP file and upload it via the WordPress plugin uploader.
Let us know if you need any further assistance. Thanks!"
